[Module #1 Homework: Docker & SQL](https://colab.research.google.com/github/Jaguar838/data-engineering-zoomcamp/blob/master/HW/01-docker-terraform/hw-01.ipynb)

##  Prepare Postgres

Run Postgres and load data as shown in the videos.
We'll use the green taxi trips from October 2019:

!wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-10.csv.gz

You will also need the dataset with zones:

!wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv

Download this data and put it into Postgres.

In [1]:
import pandas as pd
from time import time

In [2]:
from sqlalchemy import create_engine

In [12]:
df = pd.read_csv('green_tripdata_2019-10.csv.gz')

C:\Users\bober\AppData\Local\Temp\ipykernel_12784\3323436776.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('green_tripdata_2019-10.csv.gz')

In [8]:
df_iter = pd.read_csv('green_tripdata_2019-10.csv.gz', iterator=True, chunksize=100000)
df = next(df_iter)

In [10]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')
print(pd.io.sql.get_schema(df, name='green_taxi_data', con=engine))

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [44]:
while True:
    t_start = time()

    df = next(df_iter)

    df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
    df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)

    df.to_sql(name='green_taxi_data', con=engine, if_exists='append')

    t_end = time()

    print('inserted another chunk, took %.3f second' % (t_end - t_start))

NameError: name 'engine' is not defined

In [27]:
len(df)

76386

In [26]:
df.tail()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
476381,NaN,2019-10-31 23:30:00,2019-11-01 00:00:00,NaN,NaN,65,102,NaN,7.04,29.57,2.75,0.5,0.0,0.00,NaN,0.0,32.82,NaN,NaN,NaN
476382,NaN,2019-10-31 23:03:00,2019-10-31 23:24:00,NaN,NaN,129,136,NaN,0.00,39.83,2.75,0.5,0.0,6.12,NaN,0.0,49.20,NaN,NaN,NaN
476383,NaN,2019-10-31 23:02:00,2019-10-31 23:23:00,NaN,NaN,61,222,NaN,3.90,23.11,2.75,0.5,0.0,0.00,NaN,0.0,26.36,NaN,NaN,NaN
476384,NaN,2019-10-31 23:42:00,2019-10-31 23:56:00,NaN,NaN,76,39,NaN,3.08,15.23,2.75,0.5,0.0,0.00,NaN,0.0,18.48,NaN,NaN,NaN
476385,NaN,2019-10-31 23:23:00,2019-10-31 23:56:00,NaN,NaN,56,215,NaN,6.84,36.12,2.75,0.5,0.0,0.00,NaN,0.3,39.67,NaN,NaN,NaN

In [34]:
df.info( )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76386 entries, 400000 to 476385
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               0 non-null      float64
 1   lpep_pickup_datetime   76386 non-null  object
 2   lpep_dropoff_datetime  76386 non-null  object
 3   store_and_fwd_flag     0 non-null      float64
 4   RatecodeID             0 non-null      float64
 5   PULocationID           76386 non-null  int64
 6   DOLocationID           76386 non-null  int64
 7   passenger_count        0 non-null      float64
 8   trip_distance          76386 non-null  float64
 9   fare_amount            76386 non-null  float64
 10  extra                  76386 non-null  float64
 11  mta_tax                76386 non-null  float64
 12  tip_amount             76386 non-null  float64
 13  tolls_amount           76386 non-null  float64
 14  ehail_fee              0 non-null      float64
 15  improvement_surcharge  76386 non-null  float64
 16  total_amount           76386 non-null  float64
 17  payment_type           0 non-null      float64
 18  trip_type              0 non-null      float64
 19  congestion_surcharge   0 non-null      float64
dtypes: float64(16), int64(2), object(2)
memory usage: 11.7+ MB

In [35]:
df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               100 non-null    int64
 1   lpep_pickup_datetime   100 non-null    datetime64[ns]
 2   lpep_dropoff_datetime  100 non-null    datetime64[ns]
 3   store_and_fwd_flag     100 non-null    object
 4   RatecodeID             100 non-null    int64
 5   PULocationID           100 non-null    int64
 6   DOLocationID           100 non-null    int64
 7   passenger_count        100 non-null    int64
 8   trip_distance          100 non-null    float64
 9   fare_amount            100 non-null    float64
 10  extra                  100 non-null    float64
 11  mta_tax                100 non-null    float64
 12  tip_amount             100 non-null    float64
 13  tolls_amount           100 non-null    float64
 14  ehail_fee              0 non-null      float64
 15  improvement_surcharge  100 non-null    float64
 16  total_amount           100 non-null    float64
 17  payment_type           100 non-null    int64
 18  trip_type              100 non-null    int64
 19  congestion_surcharge   100 non-null    float64
dtypes: datetime64[ns](2), float64(10), int64(7), object(1)
memory usage: 15.8+ KB

In [11]:
df_zones = pd.read_csv('taxi_zone_lookup.csv')
df_zones.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [9]:
df_zones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LocationID    265 non-null    int64
 1   Borough       265 non-null    object
 2   Zone          264 non-null    object
 3   service_zone  263 non-null    object
dtypes: int64(1), object(3)
memory usage: 8.4+ KB

## Question 3. Trip Segmentation Count


During the period of October 1st 2019 (inclusive) and November 1st 2019 (exclusive), how many trips, **respectively**, happened:
1. Up to 1 mile
2. In between 1 (exclusive) and 3 miles (inclusive),
3. In between 3 (exclusive) and 7 miles (inclusive),
4. In between 7 (exclusive) and 10 miles (inclusive),
5. Over 10 miles

In [12]:
# Фільтрація за датою
start_date = pd.to_datetime('2019-10-01')
end_date = pd.to_datetime('2019-11-01')
df_filtered = df[(df['lpep_pickup_datetime'] >= start_date) & (df['lpep_pickup_datetime'] < end_date)]

In [13]:
len(df_filtered)

100

In [28]:
# Сегментування за відстанню
bins = [0, 1, 3, 7, 10, float('inf')]
labels = ['Up to 1 mile', 'Between 1 and 3 miles', 'Between 3 and 7 miles', 'Between 7 and 10 miles', 'Over 10 miles']
df_filtered['distance_category'] = pd.cut(df_filtered['trip_distance'], bins=bins, labels=labels, right=True)

# Підрахунок кількості поїздок
trip_counts = df_filtered['distance_category'].value_counts().sort_index()

In [29]:
trip_counts

distance_category
Up to 1 mile              17
Between 1 and 3 miles     45
Between 3 and 7 miles     28
Between 7 and 10 miles     7
Over 10 miles              1
Name: count, dtype: int64

Answer:

## Question 4. Longest trip for each day

Which was the pick up day with the longest trip distance?
Use the pick up time for your calculations.

Tip: For every day, we only care about one single trip with the longest distance. 

- 2019-10-11
- 2019-10-24
- 2019-10-26
- 2019-10-31

In [36]:
# Вилучення дати з часу посадки
df['pickup_date'] = df['lpep_pickup_datetime'].dt.date

In [37]:
# Групування за датою та знаходження максимальної відстані для кожного дня
max_distance_per_day = df.groupby('pickup_date')['trip_distance'].max().reset_index()

# Знаходження дати з найбільшою відстанню
longest_trip_day = max_distance_per_day.loc[max_distance_per_day['trip_distance'].idxmax()]

In [39]:
max_distance_per_day

   pickup_date  trip_distance
0   2019-10-06          34.91
1   2019-10-07          34.58
2   2019-10-08          34.75
3   2019-10-09          35.95
4   2019-10-10          32.21
5   2019-10-11          33.16
6   2019-10-12          30.15
7   2019-10-13          32.59
8   2019-10-14          43.76
9   2019-10-15          33.71
10  2019-10-16          35.41
11  2019-10-17          37.60
12  2019-10-18          31.33
13  2019-10-19          31.87
14  2019-10-20          38.29
15  2019-10-21          35.18
16  2019-10-22          36.01
17  2019-10-23          30.36
18  2019-10-24          42.14
19  2019-10-25          32.18
20  2019-10-26          32.56
21  2019-10-27          34.23
22  2019-10-28          35.31
23  2019-10-29          35.90
24  2019-10-30          34.83
25  2019-10-31          38.03

In [38]:
longest_trip_day

pickup_date      2019-10-14
trip_distance         43.76
Name: 8, dtype: object

Answer: 2019-10-26

## Question 5. Three biggest pickup zones

Which were the top pickup locations with over 13,000 in
`total_amount` (across all trips) for 2019-10-18?

Consider only `lpep_pickup_datetime` when filtering by date.
 
- East Harlem North, East Harlem South, Morningside Heights
- East Harlem North, Morningside Heights
- Morningside Heights, Astoria Park, East Harlem South
- Bedford, East Harlem North, Astoria Park

In [ ]:
df_zones.to_sql(name='zones', con=engine, if_exists='replace')

Answer:

## Question 6. Largest tip

For the passengers picked up in October 2019 in the zone
named "East Harlem North" which was the drop off zone that had
the largest tip?

Note: it's `tip` , not `trip`

We need the name of the zone, not the ID.

- Yorkville West
- JFK Airport
- East Harlem North
- East Harlem South

Answer:

## Terraform

In this section homework we'll prepare the environment by creating resources in GCP with Terraform.

In your VM on GCP/Laptop/GitHub Codespace install Terraform. 
Copy the files from the course repo
[here](../../../01-docker-terraform/1_terraform_gcp/terraform) to your VM/Laptop/GitHub Codespace.

Modify the files as necessary to create a GCP Bucket and Big Query Dataset.

## Question 7. Terraform Workflow

Which of the following sequences, **respectively**, describes the workflow for: 
1. Downloading the provider plugins and setting up backend,
2. Generating proposed changes and auto-executing the plan
3. Remove all resources managed by terraform`

Answers:
- terraform import, terraform apply -y, terraform destroy
- teraform init, terraform plan -auto-apply, terraform rm
- terraform init, terraform run -auto-approve, terraform destroy
- terraform init, terraform apply -auto-approve, terraform destroy
- terraform import, terraform apply -y, terraform rm